### ISSUE TITLE
Epic: Major Refactor

### ISSUE THREAD

**Issue by oubiwann** [clojang/clojang#1]
Been living in JVM a lot lately, and am ready to revisit this project. Here are my plans:
- Move existing master to clojure-erlastic-fork
- Create a new master (orphan branch, totally new code) that:
  1. provides an idiomatic Clojure wrapper for JInterface (probably in `clojang.jinterface`)
  2. provides a not-so-low level wrapper for this which reduces boiler plate -- hopefully significantly (probably in `clojang.erlang` and `clojang.otp`)
  3. a high-level collection of namespaces that makes creating Clojure/Erlang services a snap (not sure about namespace here just yet -- that will have to wait for now)
- Move this puppy into the lfex Github org
- Start building apps/libraries against it!

Step 0 will actually be creating an example app that uses JInterface as-is and exercises as much of it as possible (maybe even converting this to a set of system or integration tests).

Once that's working, I will begin on Step 1. The example from Step 0 will be copied and converted to use the new idiomatic Clojure wrapper for JInterface.

For interested parties, this work should be fairly easy to split up. I think that there will be basically one major namespace per JInterface class (maybe some closely related class wrappers will end up in the same namespace), so it will be fairly easy to avoid stomping on someone else's work.
## Low-level Wrapper Tasks
- [x] #2 - Create types
- [x] #3 - Wrap constants
- [x] #4 - Wrap connection and empd objects
- [x] #5 - Wrap streams and messaging
- [x] #6 - Wrap nodes, peers, and self
- [x] #7 - Wrap servers and sockets
## Mid-level Wrapper Tasks
- [ ] - TBD
## High-level Additions
- [ ] - TBD

**Comment by oubiwann** [comment]
Note that I've decided upon unit, system, and integration tests to be the "test app" ... so I've jumped right into the conversion and am writing tests side-by-side.

**Comment by oubiwann** [comment]
The low-level work has been moved to jiface. Mid-level and High-level are getting merged. Will continue to hack, but closing this ticket.
